CC=g++
CFLAGS=-Wall
STDVERSION=c++11
LINKS=-lGL -lGLU -lglut
SOURCES=main.cpp point2D.cpp segment.cpp scene.cpp vector2D.cpp
EXECUTABLE=Intersectii
     
all: 
	$(CC) $(CFLAGS) -std=$(STDVERSION) -o $(EXECUTABLE) $(SOURCES) $(LINKS)