CC=g++
CFLAGS=-Wall
STDVERSION=c++0x
LINKS=-lGL -lGLU -lglut
SOURCES=main.cpp point2d.cpp segment.cpp scene.cpp
EXECUTABLE=Intersectii
     
all: 
	$(CC) $(CFLAGS) -std=$(STDVERSION) -o $(EXECUTABLE) $(SOURCES) $(LINKS)